//import java.sql.SQLOutput;
//import java.util.IllegalFormatCodePointException;
import java.util.Scanner;
import java.util.Random;
class Game{
    int user,comp;
    int score=1;
    int noOfGuesses=0;
    public Game(){

        Random ran = new Random();
        comp=ran.nextInt(101);

    }
    public void takeUserInput(int a) {

        user = a;
        noOfGuesses++;
    }
    public void isCorrectNumber(){
        if(user==comp){
            System.out.println("Correct answer!!");

        }
        else if(user>comp){
            System.out.println("Enter a smaller number");

            score++;

        }
        else {
            System.out.println("Enter a larger number");

            score++;
        }
    }

}

public class NumberGuess {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        System.out.println("WELCOME TO GUESS THE NUMBER\nYOU HAVE TO GUESS WHAT NUMBER IS GENERATED BY COMPUTER");
        System.out.println("NOTE : YOU ONLY HAVE 8 TOTAL GUESSES");

        int choice = 1;
        int roundsWon = 0;
        int roundsPlayed =0;
        while (choice == 1){
            roundsPlayed++;
            System.out.println("Enter your number   (1=100)");
            Game g = new Game();

            int num = sc.nextInt();
            g.takeUserInput(num);
            while (g.comp != g.user && g.noOfGuesses < 8) {
                g.isCorrectNumber();
                g.takeUserInput(num = sc.nextInt());

            }
            if (g.comp == g.user) {
                System.out.println("\nCORRECT ANSWER\n");
                roundsWon++;
            }
            else {
                System.out.println("GAME OVER !!!");
                if (g.noOfGuesses >= 8) {
                    System.out.println("NO MORE GUESSES LEFT!!");
                }
            }

            System.out.println("Your took " +g.score+ " guesses.\n");


            System.out.println("Computer generated number was "+g.comp);
            System.out.println("----------------------------------------------------------------------------------------");
            System.out.println("Press 1 to PLAY NEXT ROUND \nPress 2 to EXIT");
            choice=sc.nextInt();
            if (choice==1){
                System.out.println("Next Round");

                g.noOfGuesses=0;
                g.score=0;
            } else if (choice==2) {
                System.out.println("Exiting" );
                System.out.println("Total Rounds played: "+ roundsPlayed);
                System.out.println("Total Rounds Won: "+ roundsWon);

            }
            else {
                System.out.println("Invalid choice\nExiting Anyway");
                System.out.println("Total Rounds played: "+ roundsPlayed);
                System.out.println("Total Rounds Won: "+ roundsWon);
            }
        }




    }
}

